require 'spec_helper_acceptance'

describe 'activemq' do

  describe 'running puppet code' do
    it 'should work with no errors' do
      pp = <<-EOS
        include cegekarepos::cegeka
        Yum::Repo <| title == 'cegeka-custom-noarch' |>

        package { 'yum-plugin-versionlock':
          ensure => installed
        }

        class { '::activemq':
          version           => '5.10.0-2.cgk.el6',
          data_dir          => '/usr/share/activemq/data',
          heap_dump_path    => '/usr/shared/activemq/data/heapdumps',
          manage_config     => true,
          sysconfig_options => {
            'ACTIVEMQ_OPTION1' => 'VALUE1'
          }
        }
      EOS

      # Run it twice 
      apply_manifest(pp, :catch_failures => true)
      # and test for idempotency
      apply_manifest(pp, :catch_changes => true)
    end

    describe file '/etc/activemq/activemq.xml' do
      it { is_expected.to be_file }
      its(:content) { should contain /File is generated by Puppet/ }
    end

    describe file '/etc/sysconfig/activemq' do
      it { is_expected.to be_file }
      its(:content) { should contain /ACTIVEMQ_OPTION1/ }
    end

  end
end

